image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: ignore
tasks:
  - init: yarn install
    command: yarn dev
  - command: echo split
    openMode: split-right
    name: split terminal
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
