name: Deployment tests
on:
  repository_dispatch:
    types: [check_links]

jobs:
  check-links:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Crawl site
        run: node -r esm scripts/crawl.js
        env:
          BASE_URL: ${{ github.event.client_payload.deploy_url }}

      - name: Set status
        if: always()
        run: ./.github/bin/update-status.sh ${{ job.status }} check-links 'Finished checking links'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_SHA: ${{ github.event.client_payload.commit_ref }}
