name: Link checking
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master


jobs:
  check-links:
    if: ${{ !github.event.pull_request }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        url:
          - "https://nuxtjs.org"
          - "https://id.nuxtjs.org"
          - "https://ja.nuxtjs.org"
          - "https://ko.nuxtjs.org"
          - "https://ru.nuxtjs.org"
          - "https://zh.nuxtjs.org"
          - "https://es.nuxtjs.org"
          - "https://fr.nuxtjs.org"
          - "https://pt.nuxtjs.org"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Crawl site
        run: node -r esm scripts/crawl.js
        env:
          BASE_URL: ${{ matrix.url }}

      - name: Check redirects for validity
        run: node -r esm scripts/check-redirects.js
        env:
          BASE_URL: ${{ matrix.url }}

  check-pr-links:
    if: github.event.pull_request
    strategy:
      matrix:
        site:
          - "nuxt"
          - "nuxt-id"
          - "nuxt-ja"
          - "nuxt-ko"
          - "nuxt-ru"
          - "nuxt-zh"
          - "nuxtjs-es"
          - "nuxtjs-fr"
          - "nuxtjs-pt"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitForPreview
        with:
          site_name: ${{ matrix.site }}
          max_timeout: 600

      - name: Crawl site
        run: node -r esm scripts/crawl.js
        env:
          BASE_URL: ${{ steps.waitForPreview.outputs.url }}

      - name: Check redirects for validity
        run: node -r esm scripts/check-redirects.js
        continue-on-error: ${{ matrix.site != 'nuxt' }}
        env:
          BASE_URL: ${{ steps.waitForPreview.outputs.url }}
