name: Link checking
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        url:
          - "https://nuxtjs.org"
          - "https://id.nuxtjs.org"
          - "https://ja.nuxtjs.org"
          - "https://ko.nuxtjs.org"
          - "https://ru.nuxtjs.org"
          - "https://zh.nuxtjs.org"
          - "https://es.nuxtjs.org"
          - "https://fr.nuxtjs.org"
          - "https://pt.nuxtjs.org"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Crawl site
        run: node -r esm scripts/crawl.js
        env:
          BASE_URL: ${{ matrix.url }}

      - name: Check redirects for validity
        run: node -r esm scripts/check-redirects.js
        continue-on-error: ${{ matrix.site != 'nuxt' }}
        env:
          BASE_URL: ${{ matrix.url }}
