name: textlint for Japanese documentation
on:
  pull_request:
    paths:
      - 'content/ja/**'
jobs:
  textlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint:textlint:ja
